Feature/twitter box
edstbbz/TWTReact pull request #1
Opened 2021-04-27 11:47 UTC by edstbbz

2021-04-27 11:52 UTC, gadzillllla commented on src/components/fileloader/fileLoader.jsx
> +    <>
не надо с фрагмента начинать компонент, потом будешь непредвиденное поведение на верстке ловить

2021-04-27 11:57 UTC, edstbbz commented on src/components/fileloader/fileLoader.jsx
> +    <>
А как тут иначе? Создавать ненужную div?

2021-04-27 12:02 UTC, edstbbz commented on src/components/fileloader/fileLoader.jsx
> +    <>
fixанул

2021-04-27 12:10 UTC, kpogodin commented on src/components/filepreview/fliePreview.jsx
> +  const { file, children } = props;
а зачем проптайпс установил если не спользуешь?

2021-04-27 12:10 UTC, kpogodin commented on src/components/form/form.jsx
> +    console.log(content);
ну епта

2021-04-27 12:10 UTC, kpogodin commented on src/components/form/form.jsx
> +      <Fragment key={Math.random()}>
мне кажется тебе надо почитать зачем ключ придуман в реакте и почему так ни в коем случае делать нельзя)

2021-04-27 12:10 UTC, kpogodin commented on src/components/form/form.jsx
> +      <div className="_inputs">
чотт снеймингом случилось

2021-04-27 12:10 UTC, kpogodin commented on src/components/form/form.jsx
> +          className={error}
чо в эрроре? не понял логику. почему в класснейм улетело оно

2021-04-27 12:10 UTC, gadzillllla commented on src/components/message/message.jsx
> +  className: PropTypes.string
а чилдрен?

2021-04-27 12:10 UTC, gadzillllla commented on src/components/modal/modal.jsx
> +    <>
тут тоже не начинай с фрагмента

2021-04-27 12:10 UTC, gadzillllla commented on src/components/textinput/textInput.jsx
> +      placeholder="Enter text..."
а если тебе скажут что на другой странице другой плейсхолдер будет?

2021-04-27 12:15 UTC, edstbbz commented on src/components/form/form.jsx
> +    console.log(content);
А что тут не так?

2021-04-27 12:17 UTC, edstbbz commented on src/components/form/form.jsx
> +          className={error}
Класс там

2021-04-27 12:19 UTC, pvpshoot commented on src/components/button/button.jsx
> +const Submit = (props) => {
Папки и файлы компонентов должны называться с большой буквы
Сами же констатны должны соответствовать названию файла

2021-04-27 12:19 UTC, pvpshoot commented on src/components/counter/counter.jsx
> +const Counter = (props) => {
Название файла

2021-04-27 12:19 UTC, pvpshoot commented on src/components/file/file.jsx
> +const File = (props) => {
название файла

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +          <FilePreview file={fileList.length}>{file}</FilePreview>
отвратительное апи, и по названию и по сути

2021-04-27 12:19 UTC, pvpshoot commented on src/components/filepreview/fliePreview.jsx
> +  return null;
условие выхода всегда стоит писать выше

2021-04-27 12:19 UTC, pvpshoot commented on src/components/filepreview/fliePreview.jsx
> +    return <div className="files__preview">{children}</div>;
file и children имеют разную длину?

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +  const [disbaled, setDisabled] = useState(false);
disbaled состояние или вычисляемое свойство?

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +  const addErrorClass = (text, files) => {
функции должны объявляться выше чем используются

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +    const condition = text.length + files.length * 10;
дублирование кода

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +    condition > MAX_VALUE ? setError('error') : setError('');
это вычисляемое значение

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +    if (event.keyCode === 13) {
объясни что тут происходит?

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +    list.splice(index, 1);
есть метод похожий на splice который не мутирует массив?

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +  const fileModal = (bool) => {
что за бул?

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +  const file = fileList.map((img, index) => {
файл? тут я вижу массив кода

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +          onClick={() => fileModal(true)}
имя функции должно быть глаголом

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +          onDelete={() => fileDelete(index)}
handleFileDelete звучит в разы лучше

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +  const [isOpen, setIsOpen] = useState(false);
опен что?

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +  useEffect(() => {
мы эффекты проходили?

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +        <Modal isOpen={isOpen} onClose={() => fileModal(false)}>
если будет 1000 файлов, у тебя будет 1000 модалок?

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +      <Fragment key={Math.random()}>
Math.random() это что?
зачем нужны ключи?

2021-04-27 12:19 UTC, pvpshoot commented on src/components/form/form.jsx
> +          className={error}
className={error}
что тут происходит?

2021-04-27 12:19 UTC, pvpshoot commented on src/components/message/message.jsx
> +  return <span className={className}>{children}</span>;
весь компонент это просто `<span className={className}>{children}</span>`

2021-04-27 12:19 UTC, pvpshoot commented on src/components/modal/modal.jsx
> +        <div className="modal_close" onClick={() => onClose()}>
onClick={() => onClose()}  ->  onClick={onClose}

2021-04-27 12:19 UTC, pvpshoot commented on src/components/modal/modal.jsx
> +      <div className="bg" onClick={() => onClose()} />
тоже самое

2021-04-27 12:19 UTC, pvpshoot commented on src/components/modal/modal.jsx
> +  addClass: PropTypes.string
addClass звучит как функция

2021-04-28 07:20 UTC, pvpshoot commented on src/components/filepreview/fliePreview.jsx
> +  if (children === 0) {
children: PropTypes.arrayOf(PropTypes.object)
как ты сравниваешь с 0 ?

2021-04-28 07:20 UTC, pvpshoot commented on src/components/form/form.jsx
> +  const [isOpenModal, setIsOpenModal] = useState(false);
isModalOpen

2021-04-28 07:20 UTC, pvpshoot commented on src/components/form/form.jsx
> +  const [fileForModal, setFileForModal] = useState();
невнятное название

2021-04-28 07:20 UTC, pvpshoot commented on src/components/form/form.jsx
> +          isError={errorClass}
название пропса и чтов  нем лежит

2021-04-28 09:09 UTC, pvpshoot requested changes

2021-04-28 09:09 UTC, pvpshoot commented on src/components/textinput/textInput.jsx
> +    classes.push('error');
ну чот такое себе, проще можно

2021-04-28 12:47 UTC, merged